# Copyright 2018 The KubeSphere Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.
FROM kubesphere/caddy

COPY Caddyfile.local /etc/Caddyfile
COPY ./ /srv/kubesphere.github.io/

WORKDIR /srv/kubesphere.github.io/

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]